### ISSUE TITLE
Microblink ViewController is not presenting 

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/apps-rewards-ios#63]
### Reason

We can't login

### Description

The microblink receive an viewController to present the two steps verification, but when they try to present this view, an error is throwing with this message

Attempt to present <BRNewStaticScanViewController: 0x10f83ac00> on <TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier_: 0x10c034e00> (from <TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier_: 0x10c034e00>) which is already presenting <TtGC7SwiftUI19UIHostingControllerV11TikiRewards10HomeScreen: 0x10c02f400>.

### Success Criteria

- [ ] show the two steps verification view

**Comment by ricardobrg** [comment]
this feature will be removed
